version: '3'
services:
  webhost:
    image: {acr-name}.azurecr.io/functions-container:latest
    deploy:
      replicas: 2
    ports:
      - "28000:80"      
    environment:
      AzureWebJobsStorage: '{connection-to-storage}'
      AzureWebJobsDashboard: '{connection-to-storage}'
